[[constraint]]
  branch = "master"
  name = "github.com/cashcowpro/golog"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "0.7.6"
