version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/cashcowpro/gommand
    steps:
      - checkout
      - run: go get github.com/golang/dep/cmd/dep
      - run: dep ensure -v
      - run: go test -v -race ./...
